[dark.disk]The test batch is ready.
[dark.disk]Startup
[dark.disk]Tear down
[dark.disk]The test batch is finished.
[dark.disk]******* TEST BATCH SUMMARY ********
[dark.disk]Total_test: 2; Total_test_successful: 2; Total_test_failed: 0
[dark.disk]Total execution time: 0:00:28.827000
[dark.disk]---------------------
[dark.disk]Failed tests:
[dark.disk]No test failed!
[dark.disk]---------------------
[dark.disk]Test Navigation Firefox-46_0-Darwin
[dark.disk]Test execution time: 0:00:25.448000
[dark.disk]Total_test: 2; Total_test_successful: 2; Total_test_failed: 0
[dark.disk][!]Test Navigation Firefox crashed: Traceback (most recent call last):
  File "/Users/pyrat/.virtualenvs/cob_v1/lib/python3.5/site-packages/brome/core/proxy_driver.py", line 532, in wait_until_visible
    (getattr(By, _selector.find_by), _selector.get_selector())
  File "/Users/pyrat/.virtualenvs/cob_v1/lib/python3.5/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///var/folders/jj/4xxdfpz97_x6rnv6p2vw47nh0000gn/T/tmpuc6dgo70/extensions/fxdriver@googlecode.com/components/driver-component.js:10770)
    at FirefoxDriver.prototype.findElement (file:///var/folders/jj/4xxdfpz97_x6rnv6p2vw47nh0000gn/T/tmpuc6dgo70/extensions/fxdriver@googlecode.com/components/driver-component.js:10779)
    at DelayedCommand.prototype.executeInternal_/h (file:///var/folders/jj/4xxdfpz97_x6rnv6p2vw47nh0000gn/T/tmpuc6dgo70/extensions/fxdriver@googlecode.com/components/command-processor.js:12661)
    at DelayedCommand.prototype.executeInternal_ (file:///var/folders/jj/4xxdfpz97_x6rnv6p2vw47nh0000gn/T/tmpuc6dgo70/extensions/fxdriver@googlecode.com/components/command-processor.js:12666)
    at DelayedCommand.prototype.execute/< (file:///var/folders/jj/4xxdfpz97_x6rnv6p2vw47nh0000gn/T/tmpuc6dgo70/extensions/fxdriver@googlecode.com/components/command-processor.js:12608)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pyrat/.virtualenvs/cob_v1/lib/python3.5/site-packages/brome/core/basetest.py", line 692, in execute
    self.run(**self._test_config)
  File "/Users/pyrat/Documents/PROG/PYTHON/webbase/tests/tests/test_navigation.py", line 36, in run
    self.app.logout()
  File "/Users/pyrat/Documents/PROG/PYTHON/webbase/tests/model/app.py", line 178, in logout
    self.pdriver.wait_until_visible("sv:header_register_link")
  File "/Users/pyrat/.virtualenvs/cob_v1/lib/python3.5/site-packages/brome/core/proxy_driver.py", line 548, in wait_until_visible
    raise exceptions.TimeoutException(msg)
selenium.common.exceptions.TimeoutException: Message: wait_until_visible (Selector: effective selector (//*[@name = "register-link"]), raw selector (sv:header_register_link)): element is still not visible


[dark.disk]---------------------
[dark.disk]Finished
