[sweet.tooth]The test batch is ready.
[sweet.tooth]Startup
[sweet.tooth]Tear down
[sweet.tooth]The test batch is finished.
[sweet.tooth]******* TEST BATCH SUMMARY ********
[sweet.tooth]Total_test: 0; Total_test_successful: 0; Total_test_failed: 0
[sweet.tooth]Total execution time: 0:00:22.364000
[sweet.tooth]---------------------
[sweet.tooth]Failed tests:
[sweet.tooth]No test failed!
[sweet.tooth]---------------------
[sweet.tooth]Test Navigation Firefox-46_0-Darwin
[sweet.tooth]Test execution time: 0:00:18.978000
[sweet.tooth]Total_test: 0; Total_test_successful: 0; Total_test_failed: 0
[sweet.tooth][!]Test Navigation Firefox crashed: Traceback (most recent call last):
  File "/Users/pyrat/.virtualenvs/cob_v1/lib/python3.5/site-packages/brome/core/proxy_driver.py", line 409, in wait_until_present
    (getattr(By, _selector.find_by), _selector.get_selector())
  File "/Users/pyrat/.virtualenvs/cob_v1/lib/python3.5/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///var/folders/jj/4xxdfpz97_x6rnv6p2vw47nh0000gn/T/tmpiad8nw95/extensions/fxdriver@googlecode.com/components/driver-component.js:10770)
    at FirefoxDriver.prototype.findElement (file:///var/folders/jj/4xxdfpz97_x6rnv6p2vw47nh0000gn/T/tmpiad8nw95/extensions/fxdriver@googlecode.com/components/driver-component.js:10779)
    at DelayedCommand.prototype.executeInternal_/h (file:///var/folders/jj/4xxdfpz97_x6rnv6p2vw47nh0000gn/T/tmpiad8nw95/extensions/fxdriver@googlecode.com/components/command-processor.js:12661)
    at DelayedCommand.prototype.executeInternal_ (file:///var/folders/jj/4xxdfpz97_x6rnv6p2vw47nh0000gn/T/tmpiad8nw95/extensions/fxdriver@googlecode.com/components/command-processor.js:12666)
    at DelayedCommand.prototype.execute/< (file:///var/folders/jj/4xxdfpz97_x6rnv6p2vw47nh0000gn/T/tmpiad8nw95/extensions/fxdriver@googlecode.com/components/command-processor.js:12608)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pyrat/.virtualenvs/cob_v1/lib/python3.5/site-packages/brome/core/basetest.py", line 692, in execute
    self.run(**self._test_config)
  File "/Users/pyrat/Documents/PROG/PYTHON/webbase/tests/tests/test_navigation.py", line 17, in run
    self.app.go_to_profile()
  File "/Users/pyrat/Documents/PROG/PYTHON/webbase/tests/model/app.py", line 42, in go_to_profile
    self.open_user_dropdown()
  File "/Users/pyrat/Documents/PROG/PYTHON/webbase/tests/model/app.py", line 131, in open_user_dropdown
    self.pdriver.find("sv:header_user_dropdown").click()
  File "/Users/pyrat/.virtualenvs/cob_v1/lib/python3.5/site-packages/brome/core/proxy_driver.py", line 168, in find
    elements = self.find_all(selector, **kwargs)
  File "/Users/pyrat/.virtualenvs/cob_v1/lib/python3.5/site-packages/brome/core/proxy_driver.py", line 270, in find_all
    raise_exception=raise_exception
  File "/Users/pyrat/.virtualenvs/cob_v1/lib/python3.5/site-packages/brome/core/proxy_driver.py", line 426, in wait_until_present
    raise exceptions.TimeoutException(msg)
selenium.common.exceptions.TimeoutException: Message: wait_until_present (Selector: effective selector (//*[@name = "user-dropdown"]), raw selector (sv:header_user_dropdown)): element is still not present


[sweet.tooth]---------------------
[sweet.tooth]Finished
